---
- name: Upload des fichiers du site
  become: yes
  copy: # https://docs.ansible.com/ansible/latest/modules/copy_module.html
    src: ./SiteWeb/
    dest: /var/www/html/
  notify:
    - start nginx
...